services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: dev
    ports:
      - "5430:5432"
    networks:
      - postgres


networks:
  postgres:
    driver: bridge